/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'daniel' at '3/30/17 9:29 PM' with Gradle 2.10
 *
 * @author daniel, @date 3/30/17 9:29 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
